name: Container workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: packages/container

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build container!
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          npm i
          npm run build
